In [2]:
import numpy as np

In [3]:
np. zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np. ones (10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np. full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3 ,5 ,7 ,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2]=6

In [8]:
a

array([ 1,  2,  6,  5,  7, 12])

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
n=np.array([
    [1,0,2],
    [21,5,6], 
    [5,76,8],
])
n

array([[ 1,  0,  2],
       [21,  5,  6],
       [ 5, 76,  8]])

In [20]:
n[1]=[67,67,67]
n

array([[ 1,  0,  2],
       [67, 67, 67],
       [ 5, 76,  8]])

In [21]:
n[:,2]=[69,69,69]
n

array([[ 1,  0, 69],
       [67, 67, 69],
       [ 5, 76, 69]])

In [22]:
np.random.rand(5,2)

array([[0.19416972, 0.25774601],
       [0.82006312, 0.28917315],
       [0.31785803, 0.7102374 ],
       [0.88552901, 0.47796017],
       [0.31868531, 0.18982528]])

In [23]:
np.random.seed(2)
np.random.randn(5,3)

array([[-0.41675785, -0.05626683, -2.1361961 ],
       [ 1.64027081, -1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809, -1.05795222],
       [-0.90900761,  0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545,  0.53905832]])

In [24]:
np.random.randint(low=100, high=200,  size=(6,4))

array([[133, 158, 167, 169],
       [188, 168, 146, 170],
       [195, 183, 131, 166],
       [180, 152, 176, 150],
       [104, 190, 163, 179],
       [149, 139, 146, 108]])