In [21]:
import pandas as pd
import numpy as np

In [22]:
pd.__version__

'3.0.6'

In [23]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [24]:
df.shape[0]

10000

In [25]:
df.head(1)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9


In [26]:
df.fuel_type.nunique()

3

In [27]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [28]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [29]:
median_before = df['horsepower'].median()
median_before

np.float64(254.0)

In [30]:
mode = df['horsepower'].mode()[0]
mode

np.float64(252.0)

In [31]:
df['horsepower'] = df['horsepower'].fillna(most_frequent)

In [32]:
median_after = df['horsepower'].median()
median_after

np.float64(252.0)

In [33]:
median_after - median_before

np.float64(-2.0)

In [34]:
df_asia = df[df['origin'] == 'Asia']

In [35]:
df_asia = df_asia[['vehicle_weight', 'model_year']]

In [36]:
df_asia = df_asia.iloc[:7]

In [37]:
X = df_asia.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [38]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [39]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [40]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [41]:
w = XTX_inv @ X.T @ y

In [42]:
w

array([0.13644777, 0.2327492 ])

In [43]:
w.sum()

np.float64(0.36919696904925486)