In [27]:
a=np.linspace(0,10,6)
a

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [30]:
b= np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

In [31]:
a*b

array([ 0.,  2.,  8., 18., 32., 50.])

In [34]:
a.shape[0]

6

In [47]:
def vector_vector_multiplication(a, b):
    assert a.shape[0] == b.shape[0]

    n = a.shape[0]

    result = 0

    for i in range(n):
        result = result + a[i] * b[i]
    return result

In [48]:
vector_vector_multiplication(a,b)

np.float64(110.0)